[package]
name = "limone"
version = "0.0.5"
edition = "2024"
license = "Apache-2.0"
authors = ["Matilde Morrone <contact@rosymati.com>"]
description = "Library to work with the limine boot protocol"
readme = "README.md"
documentation = "https://docs.rs/limone"
repository = "https://github.com/piuma-os/limone"
include = ["src/**/*.rs", "README.md", "LICENSE"]

[package.metadata.docs.rs]
targets = [
    "x86_64-unknown-none",
    "aarch64-unknown-none",
    "riscv64gc-unknown-none-elf",
    "loongarch64-unknown-none",
]
